//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverMst()
        {
            this.ApplicationMsts = new HashSet<ApplicationMst>();
            this.LicenseMsts = new HashSet<LicenseMst>();
        }
    
        public decimal Driver_id { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Phone_no { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string LicenseType { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public string Document { get; set; }
        public byte[] Document_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationMst> ApplicationMsts { get; set; }
        public virtual DriverMst DriverMst1 { get; set; }
        public virtual DriverMst DriverMst2 { get; set; }
        public virtual UserMst UserMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LicenseMst> LicenseMsts { get; set; }
    }
}
