//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessEntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMst()
        {
            this.ApplicationMsts = new HashSet<ApplicationMst>();
            this.DriverMsts = new HashSet<DriverMst>();
        }
    
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone_no { get; set; }
        public string Password { get; set; }
        public decimal Userid { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationMst> ApplicationMsts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverMst> DriverMsts { get; set; }
    }
}
